### ISSUE TITLE
Ошибка: The input does not contain any JSON tokens

### ISSUE THREAD

**Issue by AlexChuksin** [Tinkoff/invest-openapi-csharp-sdk#109]
Получаю ошибку: The input does not contain any JSON tokens
"The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0."

Использую код из документации, подставляя свой токен вместо my.token.
```
using Tinkoff.Trading.OpenApi.Network;
...
// токен аутентификации
var token = "my.token";
// для работы в песочнице используйте GetSandboxConnection
var connection = ConnectionFactory.GetConnection(token);
var context = connection.Context;

// вся работа происходит асинхронно через объект контекста
var portfolio = await context.PortfolioAsync();
```

**Comment by AlexanderVolkovTCS** [comment]
Попробуйте проверить, что используете токен, выпущенный для первой версии (при выпуске указано, что "для всех счетов" + "полный доступ"). Токен с ограниченными правами применяется только во второй версии.

**Comment by AlexChuksin** [comment]
Спасибо! Новый токен с полным доступом решил проблему.
